services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: npm install
    startCommand: npm start  # This runs "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: telegram-bot
